### ISSUE TITLE
Can someone documenthow to obtain NCBI username and password

### ISSUE THREAD

**Issue by whitney** [CDCgov/seqsender#16]
**Is your feature request related to a problem? Please describe.**
The seqsender submission configuration has fields for NCBI username and password. But NCBI accounts are created and logged into *vai thied party systems* (google etc). How do we obtain an NCBI username/password pair for submission to e.g. Biosample and SRA.

**Describe the solution you'd like**
Please provide documentation, or a pointer to documentation, detailing how to obtain an NCBI username/passowrd pair that would enable us to make submissions to Biosample, SRA, Genbank 

**Describe alternatives you've considered**
NA

**Additional context**
We would need the credentials to work for submissions to Biosample _and_ SRA.

**Comment by leebrian** [comment]
@dthoward96 would you please provide an estimate for if we can implement this change, and when it will be available for whitney.

**Comment by dthoward96** [comment]
@leebrian the documentation already states how to obtain credentials.

https://cdcgov.github.io/seqsender/#id_1-account-creation

**Comment by leebrian** [comment]
Thanks @dthoward96 , I reopened so @whitney  can confirm this is what they were looking for.

@whitney would you please take a look at the docs that @dthoward96 referenced and test that this works for you.

**Comment by whitney** [comment]
I had followed those instructions and the response I got was to create an account [here](https://account.ncbi.nlm.nih.gov/signup/). But as you can see the options there are all for third party authenticators which don't provide you with a username/password.

I am personally no longer blocked as a member of our BFX team has shared creds for an existing account, but if my experience above is what's expected it might be worthwhile adding some clarity to the docs. Feel free to close.

**Comment by dthoward96** [comment]
So those aren’t third party authenticators. It’s just different sign up options. Similar to how other websites let you sign up with your google, apple account etc.. 
You can choose any option to sign up for an account that works for you and your team. 

Once you have an account, you still need to request a username and password to be able to perform FTP uploads.
