### ISSUE TITLE
Clarify GISAID CLI usage

### ISSUE THREAD

**Issue by nbx0** [CDCgov/seqsender#3]
- [x] Clarify in documentation the need for users to go to gisaid.org and download their CLI-API,  where to install it for SeqSender to use it and requesting their token.

- [x] Refactor seqsender internal code to import their CLI python pkg and use their commands rather than the raw API. This will assure that changes made by GISAID get inherited to SeqSender more smoothly.

cc: @leebrian @rchau88 @kristinelacek

**Comment by dthoward96** [comment]
Setting up a meeting with @rchau88 this week to go over how this could possibly impact the docker version

**Comment by dthoward96** [comment]
GISAID users are notified to download GISAID CLI and load into seqsender
