### ISSUE TITLE
xml submissions to NCBI do not require 'org_id'

### ISSUE THREAD

**Issue by mikeyweigand** [CDCgov/seqsender#40]
**Is your feature request related to a problem? Please describe.**
xml submissions to NCBI do not require the 'org_id' field/attribute defined in `*config.yaml`. The SRA team confirmed that this number is for internal use and submitters only need to include their center/group name in the xml. 

**Describe the solution you'd like**
Remove org_id from the config and associated parsing. The recommendation from SRA team is to simplify the organization block as:

<Organization type="institute" role="owner">

**Describe alternatives you've considered**
Using the dummy value 12345 from the template appears to cause no adverse events.

**Additional context**

**Comment by dthoward96** [comment]
Thanks for the update! I've removed the field from the config file and the code for it.
