### ISSUE TITLE
can't check status

### ISSUE THREAD

**Issue by SeanSierra-Patev** [CDCgov/seqsender#48]
I'm having another issue, which I suspect may be the result of my limited experience with docker...

When I try and check the status of a submission, I get this

`docker exec -it seqsender bash seqsender-kickoff check_submission_status --submission_dir ./ --submission_name sub_1 --organism FLU

Error: Submission name: sub_1 for FLU production-data is not found in the submission log file.

Error: Either a submission has not been made or an entry has been moved.
` 

but the submission log file does exist right where I'm pointing, and contains that submission name

`cat submission_log.csv 
Submission_Name,Organism,Database,Submission_Position,Submission_Type,Submission_Date,Submission_Status,Submission_Directory,Config_File,Table2asn,GFF_File,Update_Date
sub_1,FLU,BIOSAMPLE,1,Production,2024-04-02,pending;submitted,/data,/data/sub_1/config.yaml,False,,2024-04-02
sub_1,FLU,SRA,1,Production,2024-04-02,pending;submitted,/data,/data/sub_1/config.yaml,False,,2024-04-02
sub_1,FLU,GENBANK,1,Production,2024-04-02,---;---,/data,/data/sub_1/config.yaml,False,,2024-04-02
`

**Comment by dthoward96** [comment]
Hey @SeanSierra-Patev,

There seemed to have been a typo in the docker image that was causing that. I've update the docker image so that should resolve it. I also corrected your other issue with "isolate" and "strain" names per your email. Let me know if this resolves it for you.
