### ISSUE TITLE
Use Flu Submission Org

### ISSUE THREAD

**Issue by leebrian** [CDCgov/seqsender#5]
As part of the enhancement to support flu submissions, please use a different group to identify submissions made by flu programs (as opposed to sc2 groups using CDC_OAMD).

**Comment by leebrian** [comment]
Do we have a preference for what groups we should use for Flu, or SC2, or MPox submissions? Is CDC_OAMD the only group used for SC2 submissions? Maybe you can add a section in the readme.md to call out that CDC SC2 submissions should use the CDC_OAMD group, and we can discuss internally if there's a specific flu group already. Or we may need to create one using the link you shared. I think @nbx0 mentioned that there's some discussion around this, but not sure the resolution.

**Comment by dthoward96** [comment]
We have a center account we currently use for FLU. Reina and I have gotten access and added to the group for submissions. If you have any questions about the center account, follow up with Ben as since he manages the account.
