### ISSUE TITLE
Add docs to readme and doc site about container location and availability

### ISSUE THREAD

**Issue by leebrian** [CDCgov/seqsender#74]
**Is this feature for general SeqSender usage or for submitting to a specific database, if so what database?**
General usage

**Is your feature request related to a problem? If so please describe.**
Users are unaware of container locations.

**Describe the solution you'd like**
Would you please update the readme.md and the docs site with info on where the container is published to github packages and dockerhub, and when. 

As a bonus it would be helpful to add flags to the project's readme similar to [MIRA](https://github.com/cdcgov/mira) to help users understand more about the package availability and which one they should use.
![Screenshot 2024-09-11 at 11 55 17 AM](https://github.com/user-attachments/assets/be79d6b9-b400-44f1-a8cd-f77f7000f00b)

**Additional context**
This came up after a discussion with tostadas about how to better collaborate and this seems like one of many potential enhancements that are coming up soon.

**Comment by dthoward96** [comment]
Docker file changes seems to be complete. Documentation and flags added.
