### ISSUE TITLE
Add support for new GISAID EpiFlu fields

### ISSUE THREAD

**Issue by nbx0** [CDCgov/seqsender#80]
EpiFlu now has important fields that EpiCov has had all along that need to be added to SS. 
- `Sampling strategy` 
- `Sequencing strategy`
- `Sequencing technology`
- `Assembly method`
- `Coverage`

![image](https://github.com/user-attachments/assets/e710470f-0982-4726-9095-d2f0935aa800)

cc: @rchau88 @leebrian

**Comment by dthoward96** [comment]
Updated now: https://github.com/CDCgov/seqsender/releases/tag/v1.2.2
